"""add id_created_at_updated_at_to_processed

Revision ID: 4a3bfc7322b1
Revises: 4c81d428b36a
Create Date: 2025-01-26 17:00:10.050866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3bfc7322b1'
down_revision: Union[str, None] = '4c81d428b36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_processed_data', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('page_processed_data', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('page_processed_data', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('page_processed_data', 'staging_data_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('page_processed_data', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('page_processed_data', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_page_processed_data_id'), 'page_processed_data', ['id'], unique=False)
    op.create_foreign_key(None, 'page_processed_data', 'page_staging_data', ['staging_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page_processed_data', type_='foreignkey')
    op.drop_index(op.f('ix_page_processed_data_id'), table_name='page_processed_data')
    op.alter_column('page_processed_data', 'amount',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_processed_data', 'model_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('page_processed_data', 'staging_data_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.drop_column('page_processed_data', 'updated_at')
    op.drop_column('page_processed_data', 'created_at')
    op.drop_column('page_processed_data', 'id')
    # ### end Alembic commands ###
