"""Add initial

Revision ID: 4c81d428b36a
Revises: 
Create Date: 2025-01-26 05:11:33.544904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c81d428b36a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_staging_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_path_processed', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REQUEST_ERROR', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_staging_data_id'), 'page_staging_data', ['id'], unique=False)
    op.create_table('page_processed_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_data_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staging_data_id'], ['page_staging_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_processed_data_id'), 'page_processed_data', ['id'], unique=False)
    op.create_table('page_staging_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_data_id', sa.Integer(), nullable=False),
    sa.Column('error_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staging_data_id'], ['page_staging_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_staging_log_id'), 'page_staging_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_staging_log_id'), table_name='page_staging_log')
    op.drop_table('page_staging_log')
    op.drop_index(op.f('ix_page_processed_data_id'), table_name='page_processed_data')
    op.drop_table('page_processed_data')
    op.drop_index(op.f('ix_page_staging_data_id'), table_name='page_staging_data')
    op.drop_table('page_staging_data')
    # ### end Alembic commands ###
